{% set name = "spyder" %}
{% set version = "4.0.0b6" %}
{% set sha256 = "d517583d521c8dab72c99f50586104d3fc823142f6cdc1697722d950419a58ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Prevent a crash in macOS with Python 3
    - zmq.patch

build:
  number: 0
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: True

requirements:
  host:
    - python
    - pip
  run:
    - python
    - atomicwrites
    - chardet >=2.0.0
    - cloudpickle
    - diff-match-patch
    - keyring  # [not (linux and py2k)]
    - nbconvert
    - numpydoc
    - paramiko  # [not win]
    - pexpect
    - pickleshare
    - psutil
    - pygments >=2.0
    - pylint
    - pympler
    - pyqt 5.*
    - python.app  # [osx]
    - python-language-server >=0.28.2,<0.29.0
    - pyxdg
    - pyzmq
    - qdarkstyle >=2.7
    - qtawesome >=0.5.7
    - qtconsole >=4.5.5
    - qtpy >=1.5.0
    - rtree
    - sphinx
    - spyder-kernels >=1.5.0,<1.6.0
    - watchdog

test:
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.
    Beyond its many built-in features, Spyder's abilities can be extended even
    further via first- and third-party plugins.
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
