{% set name = "spyder" %}
{% set version = "5.0.0a3" %}
{% set sha256 = "94b23e262691d3b8d5cadfa67de0b911c857b904fd788b4e7f74cddaaab7119d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Prevent a crash in macOS with Python 3
    - zmq.patch

build:
  number: 0
  entry_points:
    - spyder = spyder.app.start:main
  osx_is_app: True

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - applaunchservices >=0.1.7  # [osx]
    - atomicwrites >=1.2.0
    - chardet >=2.0.0
    - cloudpickle >=0.5.0
    - cookiecutter >=1.6.0
    - diff-match-patch >=20181111
    - intervaltree >=3.0.2
    - ipython >=7.6.0
    - jedi 0.17.2
    - jsonschema >=3.2.0
    - keyring >=17.0.0
    - nbconvert >=4.0
    - numpydoc >=0.6.0
    - paramiko >=2.4.0  # [win]
    - parso 0.7.0
    - pexpect >=4.4.0
    - pickleshare >=0.4
    - psutil >=5.3
    - pygments >=2.0
    - pylint >=1.0
    - pyls-black >=0.4.6
    - pyls-spyder >=0.3.0
    - pyqt >=5.6,<5.13
    - python.app  # [osx]
    - python-language-server >=0.36.2,<1.0.0
    - pyxdg >=0.26  # [linux]
    - pyzmq >=17
    - qdarkstyle >=2.8
    - qtawesome >=0.5.7
    - qtconsole >=5.0.1
    - qtpy >=1.5.0
    - rtree >=0.8.3
    - setuptools >=39.0.0
    - sphinx >=0.6.6
    - spyder-kernels >=1.10.1,<1.11.0
    - textdistance >=4.2.0
    - three-merge >=0.1.1
    - watchdog >=0.10.3

test:
  commands:
    - USER=test spyder -h  # [unix]
    - spyder -h  # [win]
  imports:
    - spyder

app:
  entry: spyder
  icon: logo.png
  summary: The Scientific Python Development Environment
  type: desk

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_file: LICENSE.txt
  summary: The Scientific Python Development Environment
  description: |
    Spyder is a powerful scientific environment written in Python, for Python,
    and designed by and for scientists, engineers and data analysts.
    It features a unique combination of the advanced editing, analysis,
    debugging and profiling functionality of a comprehensive development tool
    with the data exploration, interactive execution, deep inspection and
    beautiful visualization capabilities of a scientific package.
    Furthermore, Spyder offers built-in integration with many popular
    scientific packages, including NumPy, SciPy, Pandas, IPython, QtConsole,
    Matplotlib, SymPy, and more.
    Beyond its many built-in features, Spyder's abilities can be extended even
    further via first- and third-party plugins.
    Spyder can also be used as a PyQt5 extension library, allowing you to build
    upon its functionality and embed its components, such as the interactive
    console or advanced editor, in your own software.
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
